name: Deploy to Namecheap Server

on:
  push:
    branches:
      - development  # adjust branch as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install openssh-client -y

      - name: Add SSH private key to SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH connection test
        run: ssh -o StrictHostKeyChecking=no -p 21098 junecqhi@198.54.114.247 echo "SSH connection successful"

      - name: Deploy to Namecheap server
        run: scp -r -P 21098 * junecqhi@198.54.114.247:/home/junecqhi/public_html/healthy-dine
